global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: market-ingestor
    static_configs:
      - targets:
          - market-ingestor:9464

  - job_name: candle-processor
    static_configs:
      - targets:
          - candle-processor:9465
